<?php 

$crawdads = array(
	"<p>Red beans & rice ca c'est bon etoufee merci beaucoup merci beaucoup boiled crawfish boucherie jambalaya fried chicken. Viens ci okra gumbo trail ride alligator zydeco envie beignet merci beaucoup tasso Lafayette. Red beans & rice fishing gulf shrimp red beans & rice Acadiana bayou hot sauce interstate tasso. Mardi Gras beignet remoulade remoulade Fauxcheaux couillon turducken beer. Bbq bayou boiled crawfish fishing make a roux. File boudin boiled crawfish sauce piquante beignet. Remoulade sugar cane sa fait chaud sauce piquante etoufee cher. Sauce piquante fried catfish canaille gulf shrimp fais do do. 

Boiled crawfish bisque bayou sauce piquante boucherie envie. Mirliton bread pudding ca c'est bon coffee fais do do etoufee po-boy merci beaucoup bbq red beans & rice. Acadiana hunting fais do do Mardi Gras food make a roux bayou fais do do Mardi Gras andouille. Boudreaux merci beaucoup fried catfish andouille Mardi Gras alligator. Po-boy jambalaya remoulade Boudreaux praline Mardi Gras food jambalaya iced tea. Alligator gulf shrimp crawfish Acadiana make a roux Fauxcheaux andouille. Merci beaucoup viens ci boucherie boudin fishing farmer's market file gulf shrimp gumbo. 

Bisque yams couillon farmer's market crawfish po-boy okra gumbo bbq etoufee. Bbq boudin cayenne macque choux lagniappe boiled crawfish alligator. Acadiana jambalaya beignet macque choux Thibideaux boucherie sugar cane merci beaucoup bread pudding boiled crawfish. Levee King Cake yams canaille bayou. Iced tea Thibideaux fais do do catahoula Acadiana catahoula bbq. Trail ride Mardi Gras merci beaucoup smoked sausage gumbo beer boudin bread pudding boucherie andouille. Boudreaux canaille jambalaya food fried catfish cajun downtown. Jambalaya interstate boudin andouille couillon. 

Farmer's market yams lagniappe sac a lait remoulade remoulade viens ci. Crawfish Acadiana bayou yams smoked sausage praline tasso beignet sauce piquante bbq. Pecan pie remoulade lagniappe jambalaya cher sauce piquante downtown fried chicken file. Ca c'est bon boucherie smoked sausage King Cake file praline praline remoulade gulf shrimp. Acadiana cayenne fais do do farmer's market cher crawfish red beans & rice. 

Boucherie interstate alligator red beans & rice file. Pecan pie jambalaya smoked sausage bayou andouille boudin levee Boudreaux etoufee beer. Sac a lait boucherie macque choux downtown etoufee football okra gumbo Boudreaux alligator. Coffee lagniappe bayou hot sauce sugar cane red beans & rice. 

Beer po-boy cayenne Thibideaux tasso farmer's market canaille. Catahoula andouille levee lagniappe levee fried chicken fried chicken interstate Thibideaux cajun. Macque choux bourre tasso boucherie beer remoulade alligator pirogue. Bourre levee King Cake Lafayette Boudreaux iced tea bourre. Levee tasso fried chicken bayou Mardi Gras. Hunting fishing catahoula turducken gumbo levee macque choux Mardi Gras make a roux. Trail ride beer canaille file fais do do levee Lafayette Mardi Gras sauce piquante. 

King Cake football pirogue pecan pie gumbo okra gumbo trail ride levee interstate gulf shrimp. Po-boy Lafayette alligator barbed wire fried catfish bonjour. Andouille bisque King Cake fishing gulf shrimp remoulade coffee fried chicken food. Bbq cher bourre Mardi Gras coffee King Cake levee boucherie. Remoulade canaille red beans & rice sac a lait gumbo bbq. Food bayou bbq Lafayette levee jambalaya bourre bread pudding hunting. Boudin yams remoulade iced tea andouille. 

Yams fried chicken iced tea cajun viens ci red beans & rice. Fauxcheaux mirliton cayenne okra gumbo cayenne bread pudding bonjour iced tea trail ride. Bread pudding lagniappe andouille cayenne food fais do do sac a lait fried chicken trail ride. Interstate sa fait chaud downtown bayou couillon. Hunting fried catfish gumbo bread pudding coffee file. 

Remoulade fais do do po-boy cher crawfish fais do do bisque bbq make a roux boiled crawfish. Sugar cane crawfish bourre file alligator cher make a roux boiled crawfish viens ci ca c'est bon. Bonjour okra gumbo smoked sausage Mardi Gras praline. Pecan pie smoked sausage downtown fais do do boucherie catahoula. Fried catfish file bisque hot sauce sa fait chaud bayou Acadiana praline macque choux. Fauxcheaux jambalaya catahoula interstate canaille crawfish crawfish okra gumbo Acadiana jambalaya. Gulf shrimp King Cake pirogue tasso Lafayette iced tea. Hunting viens ci macque choux bread pudding interstate. 

Macque choux sa fait chaud pirogue remoulade cayenne tasso. Make a roux remoulade bbq red beans & rice po-boy. Levee pirogue fried catfish King Cake levee hunting crawfish bourre viens ci. Sa fait chaud hot sauce make a roux hot sauce cayenne. Acadiana fishing smoked sausage viens ci bread pudding Fauxcheaux Acadiana. Red beans & rice King Cake sauce piquante bbq Fauxcheaux fais do do po-boy bbq cayenne downtown. Iced tea Lafayette turducken yams Acadiana bayou catahoula bisque. 

King Cake pecan pie fais do do hot sauce Mardi Gras. Boucherie pecan pie couillon remoulade fried chicken tasso. Bisque tasso sauce piquante Boudreaux Mardi Gras interstate cayenne fishing cher catahoula. Iced tea viens ci bbq tasso Fauxcheaux iced tea. Fauxcheaux lagniappe viens ci Mardi Gras sa fait chaud bonjour Mardi Gras coffee bisque envie. 

Tasso etoufee praline macque choux gulf shrimp sauce piquante fais do do remoulade. Gumbo pirogue macque choux cajun hunting coffee hot sauce Thibideaux tasso football. Gulf shrimp cayenne trail ride red beans & rice sac a lait. Viens ci King Cake Mardi Gras tasso file Thibideaux trail ride bonjour Mardi Gras tasso. Bourre boiled crawfish cajun beignet envie. Food hunting interstate praline Mardi Gras gumbo trail ride sac a lait beer. Sac a lait football fried chicken boucherie food. Fishing boudin alligator cajun boucherie sa fait chaud barbed wire sauce piquante beer. 

Acadiana praline praline sac a lait viens ci. Barbed wire andouille smoked sausage Lafayette fried chicken. Bayou cajun cher smoked sausage zydeco praline Acadiana barbed wire barbed wire. Zydeco hunting bourre crawfish beer. Hunting smoked sausage envie mirliton yams food tasso trail ride. Levee iced tea hunting boudin smoked sausage. Okra gumbo po-boy fried catfish lagniappe boucherie yams. Macque choux pirogue zydeco jambalaya bisque merci beaucoup. 

Hunting mirliton cajun alligator crawfish fais do do bisque coffee file. Tasso fais do do bisque farmer's market red beans & rice etoufee mirliton tasso red beans & rice remoulade. Bayou trail ride boucherie boucherie canaille farmer's market andouille boucherie bayou. Yams bisque beignet levee smoked sausage smoked sausage hot sauce. Levee Acadiana bayou fishing sugar cane jambalaya mirliton farmer's market coffee. 

Remoulade bread pudding boudin interstate okra gumbo sa fait chaud mirliton sugar cane coffee. Fried chicken iced tea boiled crawfish viens ci Thibideaux okra gumbo viens ci file praline sugar cane. Andouille praline catahoula trail ride zydeco etoufee po-boy. Etoufee boudin crawfish Thibideaux remoulade smoked sausage. Pecan pie smoked sausage etoufee pirogue beer. </p>"
	);